baseurl = "https://valkiii.github.io/"
languageCode = "en-us"
title = "Valerio's Blog"
theme = "hugo-theme-casper"
paginate = 5
pluralizelisttitles = false
Copyright = "VC 2020"
canonifyurls = true
[params]
description = ["My projects.", "My thoughts.", "My recipes."]
authorlocation = "London, UK"
authorbio = "Data Scientist, Open Source enthusiast"
cover = "images/cover.jpg"
logo = "images/avatar.png"


githubName = "valkiii"
twitterName="Ciottiv"
linkedinName = "valerio-ciotti-ph-d-668b191b"
#email = "your email"
#instagramName = "your ins name"
hideHUGOSupport = false
#[[menu.main]]  # here are the buttons on the menu
#name = "Home" # Button will display as "Home"
#weight = 100 # the weight decides the position of the button (higher or lower)
#identifier = "home"
#pre = "<br />"
#url = "/"
[[menu.main]]  # here are the buttons on the menu
name = "About" # Button will display as "Home"
weight = -100 # the weight decides the position of the button (higher or lower)
identifier = "about"
url = "/about"

[[menu.main]]  # here are the buttons on the menu
name = "Publications" # Button will display as "Home"
weight = -90 # the weight decides the position of the button (higher or lower)
identifier = "publications"
url = "/publications"

[[menu.main]]  # here are the buttons on the menu
name = "Academia" # Button will display as "Home"
weight = 110 # the weight decides the position of the button (higher or lower)
identifier = "academia"
#pre = "<h3>Previously</h3>"
url = "/academia"
[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
#pre = "<h3>Currently</h3>"
url = "/post"
weight = 105

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
