baseurl = "https://valkiii.github.io/"
languageCode = "en-us"
title = "Valerio's Blog"
theme = "hugo-theme-casper"
paginate = 2
Copyright = "VC 2020"
canonifyurls = true
[params]
description = ["My projects.", "My thoughts.", "My recipes."]
authorlocation = "authorlocation"
cover = "images/cover.jpg"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/avatar.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
githubName = "valkiii"
twitterName="Ciottiv"
linkedinName = "valerio-ciotti-ph-d-668b191b"
#email = "your email"
#instagramName = "your ins name"
hideHUGOSupport = false
[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"
[[menu.main]]  # here are the buttons on the menu
name = "About" # Button will display as "Home"
weight = 60 # the weight decides the position of the button (higher or lower)
identifier = "about"
pre = "<br />"
url = "/about"
[[menu.main]]  # here are the buttons on the menu
name = "Academia" # Button will display as "Home"
weight = 60 # the weight decides the position of the button (higher or lower)
identifier = "academia"
pre = "<br />"
url = "/academia"
[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"
[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/post"
weight = 40
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
